source 'http://rubygems.org'

gem 'sqlite3'
gem 'test-unit', '=1.2.3', :platforms => :ruby_19 # satisfy Travis CI
gem 'rails', '~>2.3.10'
gem 'rspec', '<2'
gem 'rspec-rails', '<2'
gem 'rspec_candy'
gem 'haml', '=3.0.25'
gem 'rails_xss'
gem 'angular_xss', :path => '../..'
